const resp=$input.first().json;
const pl=$('Prep Lookup').first().json;
const leadEmail=(pl.lead_email||'').toLowerCase();
const sd=$getWorkflowStaticData('global');
const all=(resp&&(resp.data||resp.emails))||[];
const emails=all.filter(m=>String(m.lead||'').toLowerCase()===leadEmail);
if(!leadEmail||!emails.length) return [{ json: { prospectId: pl.prospectId, _skip:true } }];
const rawBody=(m)=>{if(typeof m.text_body==='string'&&m.text_body.trim())return m.text_body;let h='';if(m.body&&typeof m.body==='object')h=(typeof m.body.text==='string'&&m.body.text.trim())?m.body.text:(m.body.html||'');else if(typeof m.body==='string')h=m.body;else h=m.snippet||'';h=h.replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<[^>]*>/g,' ');return h;};
const clean=(t)=>{if(!t)return '';let s=String(t);s=s.replace(/(?:\r?\n|\s)On\s+\S.{0,170}?wrote:[\s\S]*$/i,'');s=s.replace(/\n\s*>[\s\S]*$/,'');s=s.replace(/(?:\r?\n|^)From:\s[\s\S]*$/i,'');s=s.replace(/[a-z]+\\?:\s*\{behavior:url\([^)]*\)[^}]*\}/gi,'');s=s.replace(/[.#]?[a-z][\w-]*\s*\{[^}]*\}/gi,'');s=s.replace(/https?:\/\/\S+/g,'');s=s.replace(/&nbsp;/gi,' ').replace(/&[a-z#0-9]+;/gi,' ');s=s.replace(/Sent from my iPhone/gi,'');return s.replace(/\s+/g,' ').trim();};
const fromOf=(m)=>{if(typeof m.from==='string')return m.from;if(Array.isArray(m.from_address_json)&&m.from_address_json[0])return m.from_address_json[0].address||'';return m.from_address_email||m.from_email||'';};
const isIn=(m)=>{const d=String(m.direction||'').toUpperCase();if(d==='IN')return true;if(d==='OUT')return false;return fromOf(m).toLowerCase().includes(leadEmail);};
const sorted=[...emails].sort((a,b)=>new Date(a.sent_on||a.timestamp_created||a.created_at||0)-new Date(b.sent_on||b.timestamp_created||b.created_at||0));
const lines=sorted.map(m=>{const dt=String(m.sent_on||m.timestamp_created||m.created_at||'').slice(0,10);const dir=isIn(m)?'THEM':'US';const body=clean(rawBody(m)).slice(0,260);return '['+dt+'] '+dir+': '+body;}).filter(l=>l.replace(/\[.*?\] (THEM|US): /,'').length>3);
let thread_context=lines.join('\n\n');
if(thread_context.length>6000)thread_context=thread_context.slice(-6000);
if(!thread_context) return [{ json: { prospectId: pl.prospectId, _skip:true } }];
const current=''+(($('Loop Prospects').first().json.fields||{})['Conversation Thread']||'');
if(thread_context.trim()===current.trim()) return [{ json: { prospectId: pl.prospectId, _skip:true } }];
sd.threadSync.updated++;
return [{ json: { prospectId: pl.prospectId, 'Conversation Thread': thread_context } }];