const pr=$('Loop Prospects').first().json||{};
const prf=pr.fields||pr;
const ct=$input.first().json||{};
const cf=ct.fields||ct;
const sd=$getWorkflowStaticData('global');
sd.threadSync.checked++;
const clientIds=Array.isArray(prf.Client)?prf.Client:[];
const cm=(sd.clientMap||{})[clientIds[0]]||{};
const lead_email=String(cf.email||'').toLowerCase().trim();
if(!sd.threadSync.problems) sd.threadSync.problems=[];
if(!lead_email) sd.threadSync.problems.push((prf.Name||pr.id)+': contact fetch returned no email');
else if(!cm.pvWorkspace) sd.threadSync.problems.push((prf.Name||pr.id)+': client has no PV workspace');
return [{ json: { prospectId:pr.id||'', prospectName:prf.Name||'', lead_email, pvWorkspace:cm.pvWorkspace||'' } }];