#!/usr/bin/env node
// Rootworks actors index.
// Reads every card under actors/<platform>/<Actor>/card.json and writes actors/INDEX.md: actor,
// platform, ours or rented, what it feeds, its schedule, description. Do not hand-edit the index.
//
// Usage: node scripts/actors/index.js

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..', '..', 'actors');
const cell = (s) => String(s || '').replace(/\|/g, '\\|').replace(/\s+/g, ' ').trim();

const rows = [];
for (const platform of fs.readdirSync(ROOT)) {
  const p = path.join(ROOT, platform);
  if (!fs.statSync(p).isDirectory()) continue;
  for (const name of fs.readdirSync(p)) {
    const file = path.join(p, name, 'card.json');
    if (!fs.existsSync(file)) continue;
    const card = JSON.parse(fs.readFileSync(file, 'utf8'));
    rows.push({ dir: `${platform}/${name}`, card, src: fs.existsSync(path.join(p, name, 'src')) });
  }
}
rows.sort((a, b) => a.card.name.localeCompare(b.card.name));

const lines = [
  '# actors',
  '',
  'Generated by `scripts/actors/index.js` from the cards. Do not hand-edit. An actor is a source: it scrapes a signal and its task\'s webhook hands the run to a Rootflow\'s door.',
  '',
  '| Actor | Platform | Ours | Feeds | Schedule | Description |',
  '|---|---|---|---|---|---|',
];
for (const r of rows) lines.push(`| [${cell(r.card.name)}](${encodeURI(r.dir)}/card.json) | ${cell(r.card.platform)} | ${r.card.ours ? (r.src ? 'yes, source in src/' : 'yes, source missing') : 'rented'} | ${cell(r.card.feeds)} | ${cell(r.card.schedule)} | ${cell(r.card.description)} |`);
fs.writeFileSync(path.join(ROOT, 'INDEX.md'), lines.join('\n') + '\n');
console.log(`${rows.length} actor(s) -> actors/INDEX.md`);
