const BBOK=['deliverable','undeliverable','risky','unknown'];
const initAll=$('Init').all();
const t0=(initAll[0]&&initAll[0].json._t0)||Date.now();
const elapsed=Date.now()-t0;
const MAX=3600000;
const polls=$input.all();
const out=polls.map((p,idx)=>{ const j=p.json||{}; const init=(initAll[idx]&&initAll[idx].json)||{}; const id=init.id||j.id||''; const email=init.email||j.email||''; const res=BBOK.includes(j.result)?j.result:''; return {j,res,ready:!!res,id,email}; });
const anyPending=out.some(e=>!e.ready&&e.id)&&elapsed<MAX;
const w=elapsed<30000?15:elapsed<120000?30:elapsed<300000?60:180;
return out.map(e=>({ json:{ email:e.email, id:e.id, result: e.ready?e.res:(anyPending?'':(e.id?((e.j.result||e.j.state)||'risky'):'error')), state: e.ready?e.res:(anyPending?'':(e.id?((e.j.result||e.j.state)||'risky'):'error')), raw:e.j, _loop:anyPending, _nextWaitSec:w } }));