const stripCite=(t)=>String(t||'').replace(/[-]/g,'').replace(/cite(turn\d+\w+?\d+)+/gi,'').replace(/turn\d+(?:view|search|news|image|video|product|ref)\d+/gi,'').replace(/cite/gi,'').replace(/ {2,}/g,' ').trim();
const stripEmoji=(t)=>String(t||'').replace(/:[a-z0-9_+-]+:/gi,'').replace(/[\u{1F000}-\u{1FAFF}\u{2600}-\u{27BF}\u{2B00}-\u{2BFF}\u{2190}-\u{21FF}\u{2300}-\u{23FF}\u{FE0F}\u{200D}]/gu,'').replace(/ {2,}/g,' ').trim();
const q=($input.first().json||{}).output||{};
const n=$('Normalize Booking').first().json;
const p=$('Resolve Prospect').first().json;
const status=String(q.qualification_status||'');
const qualificationStatus=({strong:'Qualified',medium:'Needs Review',weak:'Needs Review',out_of_icp:'Disqualified'})[status]||'Needs Review';
const vlabel=({strong:'Qualified',medium:'Qualified (medium confidence)',weak:'Qualified (weak fit)',out_of_icp:'Not qualified'})[status]||'Needs review';
const vreason=stripEmoji(stripCite(q.verdict_reason||'')).slice(0,200);
const brief=stripCite(q.slack_brief_markdown||'').slice(0,2800);
const briefLines=(vlabel+(vreason?': '+vreason:'')+'\n\n'+stripEmoji(brief)).split('\n').map(s=>s.trim()).filter(Boolean);
const briefMd=briefLines.length?(['**'+briefLines[0]+'**',''].concat(briefLines.slice(1).map(l=>'- '+l))).join('\n'):'';
const when=(n.startTime||'').slice(0,16).replace('T',' ');
const line='Booked via '+n.source+' on '+$now.toFormat('yyyy-MM-dd')+': '+(n.title||'(untitled)')+' at '+(when||'?')+(n.meetingUrl?' | '+n.meetingUrl:'')+'. Attribution: '+(p.tier||'Unattributed')+(p.why?' ('+p.why+')':'')+'. Verdict: '+qualificationStatus+(vreason?' ('+vreason+')':'')+'.';
const contextNotes=((p.priorNotes||'').trim()?(p.priorNotes.trim()+'\n\n'):'')+line;
return [{ json:{ qualificationStatus, verdict:status, verdictReason:vreason, briefMd, brief, situation:stripCite(q.situation_summary||'').slice(0,200), recommended:stripCite(q.recommended_action||'').slice(0,300), timezone:String(q.timezone||''), companyName:String(q.company_name||''), contextNotes, attributionLine:line } }];
